#!/bin/bash

PETSC_ARCH="opt"
WARNING="-w"

for arg in $@ ; do
    if [[ "$arg" == "-d" ]]; then
        PETSC_ARCH="dbg"
        OPT_FLAGS="-Og"
        DEBUG_FLAGS="-g3 -rdynamic"
    elif [[ "$arg" == "-w" ]]; then
        WARNING="-Wall"
    elif [[ "$arg" == "-n" ]]; then
        NOMAKE=1
    elif [[ "$arg" == "-c" ]]; then
        CLEAN=1
    fi
done



export CFLAGS="$WARNING $DEBUG_FLAGS $OPT_FLAGS"
export CXXFLAGS="-std=c++11 $WARNING $DEBUG_FLAGS $OPT_FLAGS"



function config_intruder {
    module load mvapich2-2.1/gcc-4.9.2
    export CC=mpicc
    export CXX=mpicxx
    export CFLAGS="-std=gnu11 $CFLAGS"
    CONF="--with-mpi --with-petsc-dir=/opt/petsc-3.11.0-mpich2 --with-hdf4-dir=/opt/hdf --with-gd-dir=/opt/gd --with-cgal-dir=/opt/cgal --with-boost-dir=/opt/boost-1.58.0 --with-arma-inc=/opt/armadillo-9/include --with-arma-lib=/opt/armadillo-9/lib64 --with-cvode-dir=/opt/cvode --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib64"
}

function config_omega {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${PETSC_ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_lambda {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${PETSC_ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_alpha {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${PETSC_ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_beta {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${PETSC_ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_grad01 {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${PETSC_ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_jarretlaptop {
	PETSC_DIR="/home/jarret/petsc-3.11.0-dbg"
    	export CC=${PETSC_DIR}/bin/mpicc
    	export CXX=${PETSC_DIR}/bin/mpicxx
    	CONF="--with-mpi --with-petsc-dir=${PETSC_DIR}"
}

function config_defiant {
    PETSC_DIR="/opt/petsc-3.11.0-${PETSC_ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/opt/hdf-4.2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

HOST=`uname -n`

if [[ "$HOST" == intruder.cluster ]]; then
    echo "Machine recognized as intruder."
    config_intruder
elif [[ "$HOST" == omega.ams.stonybrook.edu ]]; then
    echo "Machine recognized as omega."
    config_omega
elif [[ "$HOST" == lambda ]]; then
    echo "Machine recognized as lambda."
    config_lambda
elif [[ "$HOST" == alpha ]]; then
    echo "Machine recognized as alpha."
    config_alpha
elif [[ "$HOST" == beta.ams.stonybrook.edu ]]; then
    echo "Machine recognized as beta."
    config_beta
elif [[ "$HOST" == defiant ]]; then
    echo "Machine recognized as defiant."
    config_defiant
elif [[ "$HOST" == grad01 ]]; then
    echo "Machine recognized as grad01."
    config_grad01
elif [[ "$HOST" == jarret-MacBookAir ]]; then
	echo "Jarret RECOGNIZED"
	config_jarretlaptop
else 
    echo Unreognized machine.
    echo "Type the PETSc directory to use (opt, dbg):"
    read PETSC_DIR
    echo using ${PETSC_DIR} 
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR}"
fi



if [[ -n "$CLEAN" ]]; then
    make clean
fi

autoreconf -vif

echo "configure options: ${CONF}"

./configure ${CONF}

if [[ -z "$NOMAKE" ]]; then
    make
fi

