#!/bin/bash

source ~/.bashrc


for arg in $@ ; do
    if [[ "$arg" == "-d" ]]; then
        DEBUG_FLAGS="-g3 -rdynamic"
        OPT_FLAGS="-Og"
    elif [[ "$arg" == "-n" ]]; then
        NOMAKE=1
    elif [[ "$arg" == "-c" ]]; then
        CLEAN=1
    elif [[ "$arg" == "-CD_OFF" ]]; then
        DISABLED="-DCOLLISION_DETECTION_OFF"
        echo "Collision detection disabled."
    fi
done


export CC=mpicc
export CFLAGS="-w $DEBUG_FLAGS $OPT_FLAGS"

export CXX=mpicxx
export CXXFLAGS="-std=c++11 -w $DEBUG_FLAGS $OPT_FLAGS"

export CPPFLAGS=$DISABLED


function config_intruder {
    CFLAGS="-std=gnu11 $CFLAGS"
    CONF="--with-mpi --with-petsc-dir=/opt/petsc3.5.4-mpich2 --with-hdf4-dir=/opt/hdf --with-gd-dir=/opt/gd --with-cgal-inc=/opt/cgal-4.11.1/include --with-cgal-lib=/opt/cgal-4.11.1/lib64 --with-boost-dir=/opt/boost-1.58.0 --with-arma-inc=/opt/armadillo-9/include --with-arma-lib=/opt/armadillo-9/lib64 --with-cvode-dir=/opt/cvode --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib64"
}

function config_omega {
    CONF="--with-mpich-dir=/usr/local/pkg/mpich2-3.2 --with-petsc-dir=/usr/local/pkg/petsc-3.10.5 --with-hdf4-dir=/usr/local/pkg/hdf --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib --with-nlopt-inc=/usr/local/include --with-nlopt-lib=/usr/local/lib"
}

function config_lambda {
    CONF="--with-mpich-dir=/usr/local/pkg/mpich2-3.2 --with-petsc-dir=/usr/local/pkg/petsc --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_alpha {
    CONF="--with-mpich-dir=/usr/local/pkg/mpich-3.2.1 --with-petsc-dir=/usr/local/pkg/petsc-3.10.5 --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_grad01 {
    CONF="--with-mpich-dir=/usr/local/mpich-3.3 --with-petsc-dir=/usr/local/petsc-3.1-p8 --with-hdf4-dir=/usr/local/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_defiant {
    CONF="--with-mpich-dir=/usr/local/mpich-3.2.1 --with-petsc-dir=/usr/local/petsc --with-hdf4-dir=/usr/local/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}


HOST=`uname -n`

if [[ "$HOST" == intruder.cluster ]]; then
    echo "Machine recognized as intruder."
    config_intruder
elif [[ "$HOST" == omega.ams.stonybrook.edu ]]; then
    echo "Machine recognized as omega."
    config_omega
elif [[ "$HOST" == lambda ]]; then
    echo "Machine recognized as lambda."
    config_lambda
elif [[ "$HOST" == alpha ]]; then
    echo "Machine recognized as alpha."
    config_alpha
elif [[ "$HOST" == defiant ]]; then
    echo "Machine recognized as defiant."
    config_defiant
elif [[ "$HOST" == grad01 ]]; then
    echo "Machine recognized as grad01."
    config_grad01
fi


autoreconf -vif

echo "configure options: ${CONF}"

./configure ${CONF}

if [[ -n "$CLEAN" ]]; then
    make clean
fi

if [[ -z "$NOMAKE" ]]; then
    make
fi

