#!/bin/bash

###########################################################
##                  Config Functions                     ##
###########################################################


function config_opportunity {
    OPENMPI_DIR=/shared/openmpi-2.1.1/gcc-6.2.1
    export CC="${OPENMPI_DIR}/bin/mpicc"
    export CXX="${OPENMPI_DIR}/bin/mpicxx"
    export CFLAGS="-std=gnu11 $CFLAGS"
    CONF="--with-openmpi-dir=${OPENMPI_DIR} --with-gd-dir=/home/ext.bballentine/FT_External/gd-2.2.5 --with-hdf4-dir=/home/ext.bballentine/FT_External/hdf4-2.10 --with-cgal-inc=/home/ext.bballentine/FT_External/CGAL-4.14/include --with-cgal-lib=/home/ext.bballentine/FT_External/CGAL-4.14/lib64 --with-arma-inc=/home/ext.bballentine/FT_External/armadillo-9/include --with-arma-lib=/home/ext.bballentine/FT_External/armadillo-9/lib64"
}

function config_opportunity_serial {
    export CFLAGS="-std=gnu11 $CFLAGS"
    CONF="--with-gd-dir=/home/ext.bballentine/FT_External/gd-2.2.5 --with-hdf4-dir=/home/ext.bballentine/FT_External/hdf4-2.10 --with-cgal-inc=/home/ext.bballentine/FT_External/CGAL-4.14/include --with-cgal-lib=/home/ext.bballentine/FT_External/CGAL-4.14/lib64 --with-arma-inc=/home/ext.bballentine/FT_External/armadillo-9/include --with-arma-lib=/home/ext.bballentine/FT_External/armadillo-9/lib64"
}

function config_intruder {
    module load mvapich2-2.1/gcc-4.9.2
    export CC=mpicc
    export CXX=mpicxx
    export CFLAGS="-std=gnu11 $CFLAGS"
    CGAL_DIR="/opt/CGAL-4.14"
    CONF="--with-mpi --with-petsc-dir=/opt/petsc-3.11.0-mpich2 --with-hdf4-dir=/opt/hdf --with-gd-dir=/opt/gd --with-cgal-inc=${CGAL_DIR}/include --with-cgal-lib=${CGAL_DIR}/lib64 --with-boost-dir=/opt/boost-1.65.1 --with-arma-inc=/opt/armadillo-9/include --with-arma-lib=/opt/armadillo-9/lib64 --with-cvode-dir=/opt/cvode --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib64"
}

function config_omega {
    CGAL_DIR="/usr/local/pkg/CGAL-4.14-${ARCH}"
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-dir=${CGAL_DIR} --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_lambda {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_alpha {
    CGAL_DIR="/usr/local/pkg/CGAL-4.14-${ARCH}"
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-dir=${CGAL_DIR} --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_beta {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/pkg/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_grad01 {
    PETSC_DIR="/usr/local/pkg/petsc-3.11.0-${ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/usr/local/hdf4-2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-inc=/usr/include --with-cgal-lib=/usr/lib/x86_64-linux-gnu --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib/x86_64-linux-gnu --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}

function config_jarretlaptop {
	PETSC_DIR="/home/jarret/petsc-3.11.0-dbg"
    	export CC=${PETSC_DIR}/bin/mpicc
    	export CXX=${PETSC_DIR}/bin/mpicxx
    	CONF="--with-mpi --with-petsc-dir=${PETSC_DIR}"
}

function config_defiant {
    CGAL_DIR="/opt/CGAL-4.14-${ARCH}"
    PETSC_DIR="/opt/petsc-3.11.0-${ARCH}"
    export CC=${PETSC_DIR}/bin/mpicc
    export CXX=${PETSC_DIR}/bin/mpicxx
    CONF="--with-mpi --with-petsc-dir=${PETSC_DIR} --with-hdf4-dir=/opt/hdf-4.2.10 --with-gd-inc=/usr/include --with-gd-lib=/usr/lib/x86_64-linux-gnu --with-cgal-dir=${CGAL_DIR} --with-arma-inc=/usr/include --with-arma-lib=/usr/lib --with-cvode-inc=/usr/include --with-cvode-lib=/usr/lib --with-nlopt-inc=/usr/include --with-nlopt-lib=/usr/lib/x86_64-linux-gnu"
}


###########################################################
##                   Start of Script                     ##
###########################################################


ARCH="opt"
OPT_FLAGS="-O2"

DEBUG_FLAGS="-rdynamic"
WARNING="-w"


for arg in $@ ; do
    if [[ "$arg" == "-d" ]]; then
        ARCH="dbg"
        OPT_FLAGS="-Og"
        DEBUG_FLAGS="-gdwarf-2 -g3 -rdynamic"
    elif [[ "$arg" == "-w" ]]; then
        WARNING="-Wall"
    elif [[ "$arg" == "-n" ]]; then
        NOMAKE=1
    elif [[ "$arg" == "-s" ]]; then
        SERIAL=1
    fi
done


export CFLAGS="$WARNING $DEBUG_FLAGS $OPT_FLAGS"
export CXXFLAGS="-std=c++11 $WARNING $DEBUG_FLAGS $OPT_FLAGS"


HOST=$(uname -n)


if [[ "$HOST" == intruder.cluster ]]; then
    echo "Machine recognized as intruder."
    config_intruder
elif [[ "$HOST" == omega.ams.stonybrook.edu ]]; then
    echo "Machine recognized as omega."
    config_omega
elif [[ "$HOST" == lambda ]]; then
    echo "Machine recognized as lambda."
    config_lambda
elif [[ "$HOST" == alpha ]]; then
    echo "Machine recognized as alpha."
    config_alpha
elif [[ "$HOST" == beta.ams.stonybrook.edu ]]; then
    echo "Machine recognized as beta."
    config_beta
elif [[ "$HOST" == defiant ]]; then
    echo "Machine recognized as defiant."
    config_defiant
elif [[ "$HOST" == grad01 ]]; then
    echo "Machine recognized as grad01."
    config_grad01
elif [[ "$HOST" == jarret-MacBookAir ]]; then
	echo "Jarret RECOGNIZED"
	config_jarretlaptop
elif [[ "$HOST" == head ]]; then
    echo "Machine recognized as opportunity."
    if [[ "$SERIAL" == 1 ]]; then
        config_opportunity_serial
    else
        config_opportunity
    fi
else 
    echo Unrecognized machine.
    exit 1
fi


autoreconf -vif

echo "configure options: ${CONF}"

./configure ${CONF}

if [[ "$NOMAKE" != 1 ]]; then
    make -j 4
fi

