#!/bin/bash

#SBATCH --job-name=serial_job_test     # Job name
#SBATCH --ntasks=1                     # Run on single cpu
#SBATCH --mem-per-cpu=6G             # memory per cpu-core
#SBATCH --output=serial_test_%j.log    # Path to the standard output and error files relative to the working directory

DIR=$(pwd)
EXE="cairfoil"

if [ "$#" -ne 1 ]; then
    echo "Error: must provide input file as argument"
    exit -1;
fi

INFILE=$1
BASENAME=${INFILE#in-}
OUTDIR="out-${BASENAME}-serial"

echo "Date              = $(date)"
echo "Hostname          = $(hostname -s)"
echo "Working Directory = $DIR"
echo "Executable = $EXE"
echo "Input File = $INFILE"
echo "Output Directory = $OUTDIR"
echo ""
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"
echo ""

module load mvapich2/2.3.3-gcc-8.3.1
#export LD_LIBRARY_PATH="/opt/sundials/sundials-2.7.0-opt/lib:/opt/petsc/petsc-3.13.4-opt/lib:/usr/lib64:$LD_LIBRARY_PATH"
echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
echo ""

echo "$DIR/$EXE -d 3 -i $DIR/$INFILE -o $OUTDIR"

$DIR/$EXE -d 3 -i $DIR/$INFILE -o $OUTDIR

