#!/bin/bash


#executable
EXENAME="matdata"

#input directory 
INDIR=${1%/}

if [ "$#" -ne 1 ]; then
    echo "Error: incorrect number of input arguments"
    exit -1;
elif [ ! -d "$INDIR" ]; then
    echo "Error: input directory does not exist"
    exit -1
fi

DIR=`pwd`
EXE="$DIR/$EXENAME"
QRUNDIR="$INDIR/qrun-serial"
PARENTOUTDIR="$DIR/out-$INDIR-serial"

echo -e "path to executable:\n\t $EXE\n"
echo -e "directory containing the input files:\n\t $INDIR\n"
echo -e "directory where qrun files will be generated:\n\t $QRUNDIR\n"
echo -e "directory to write output of each run:\n\t $PARENTOUTDIR\n"
mkdir -p $QRUNDIR
mkdir -p $PARENTOUTDIR

QRUNHEADER="$QRUNDIR/qrunheader.txt"
echo '#!/bin/bash' > $QRUNHEADER
echo '#$ -q nodes.q' >> $QRUNHEADER
echo '#$ -R y' >> $QRUNHEADER
echo -e '#$ -cwd\n' >> $QRUNHEADER
echo 'source /etc/profile.d/modules.sh' >> $QRUNHEADER
echo -e 'source /act/etc/profile.d/actbin.sh\n' >> $QRUNHEADER
echo -e 'module load mvapich2-2.1/gcc-4.9.2\n' >> $QRUNHEADER
echo -e 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/szip/lib:/opt/armadillo-9/lib64:/opt/OpenBLAS/lib:/opt/cgal/lib:/opt/boost-1.58.0/lib:/opt/petsc-3.11.0-mpich2/lib:/opt/cuda/lib64:/opt/hdf/lib:/opt/gd/lib:/usr/lib64\n' >> $QRUNHEADER

for infile in "$INDIR"/in-* ; do
    infile=`basename "$infile"`
    outdir="$PARENTOUTDIR/out-$infile"; mkdir -p $outdir
    qrunfile="$QRUNDIR/qrun-$infile"
    jobname="$EXENAME-$infile"
    cat $QRUNHEADER > $qrunfile
    echo -e "\n$EXE -d 1 -i $INDIR/$infile -o $outdir" >> $qrunfile
    chmod 700 $qrunfile
    qsub -N $jobname -o $outdir/qsubout -e $outdir/qsuberror $qrunfile
done



