#!/bin/bash

#SBATCH --job-name=cFluid-p224-%j     # Job name
#SBATCH --ntasks=16                     # Number of MPI tasks (i.e. processes
#SBATCH --cpus-per-task=1               # Number of cores per MPI task
#SBATCH --nodes=2                       # Maximum number of nodes to be allocated
#SBATCH --output=cFluid-p224-%j.log   # Path to the standard output and error files relative to the working directory


EXE="cFluid"
DIR=$(pwd)


if [ "$#" -ne 3 ]; then
    echo "Error: must provide input file restart directory and restart step as arguments"
    exit -1;
fi

INFILE=$1
BASENAME=${INFILE#in-}

RESTARTDIR=${2%/}
RESTARTSTEP=$3

OUTDIR="out-${BASENAME}-restart-ts$RESTARTSTEP-p224"


echo "Date              = $(date)"
echo "Hostname          = $(hostname -s)"
echo "Working Directory = $DIR"
echo "Executable = $EXE"
echo "Input File = $INFILE"
echo "Output Directory = $OUTDIR"
echo ""
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"
echo ""


module load mvapich2/2.3.3-gcc-8.3.1

echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
echo ""

echo "mpiexec -np 16 $DIR/$EXE -d 3 -p 2 2 4 -i $DIR/$INFILE -o $OUTDIR -r $RESTARTDIR -t $RESTARTSTEP"

mpiexec -np 16 $DIR/$EXE -d 3 -p 2 2 4 -i $DIR/$INFILE -o $OUTDIR -r $RESTARTDIR -t $RESTARTSTEP


STAT_FILE="$OUTDIR/mem_stats.txt"
sstat -j $SLURM_JOB_ID.batch --format=JobID,MaxVMSize > $STAT_FILE

