#!/bin/bash

#SBATCH --job-name=cFluid-p22-%j       # Job name
#SBATCH --ntasks=4                      # Number of MPI tasks (i.e. processes
#SBATCH --cpus-per-task=1               # Number of cores per MPI task
#SBATCH --nodes=1                       # Maximum number of nodes to be allocated
#SBATCH --output=cFluid-p22-%j.log     # Path to the standard output and error files relative to the working directory


EXE="cFluid"
DIR=$(pwd)


if [ "$#" -ne 1 ]; then
    echo "Error: must provide input file as argument"
    exit -1;
fi

INFILE=$1
BASENAME=${INFILE#in-}
OUTDIR="out-${BASENAME}-p22"


echo "Date              = $(date)"
echo "Hostname          = $(hostname -s)"
echo "Working Directory = $DIR"
echo "Executable = $EXE"
echo "Input File = $INFILE"
echo "Output Directory = $OUTDIR"
echo ""
echo "Number of Nodes Allocated      = $SLURM_JOB_NUM_NODES"
echo "Number of Tasks Allocated      = $SLURM_NTASKS"
echo "Number of Cores/Task Allocated = $SLURM_CPUS_PER_TASK"
echo ""


module load mvapich2/2.3.3-gcc-8.3.1

echo "LD_LIBRARY_PATH = $LD_LIBRARY_PATH"
echo ""

echo "mpiexec -np 4 $DIR/$EXE -d 2 -p 2 2 -i $DIR/$INFILE -o $OUTDIR"


mpiexec -np 4 $DIR/$EXE -d 2 -p 2 2 -i $DIR/$INFILE -o $OUTDIR


