#!/bin/bash
#$ -q all.q
#$ -R y
#$ -pe mpi 4
#$ -cwd
#$ -N parachute-221

source /etc/profile.d/modules.sh
source ~/.bashrc

DIR=`pwd`


mpirun -np 4 $DIR/parachute -d 3 -p 2 2 1 -i $DIR/in-C9-VnG-box -o $DIR/out-C9-VnG-box-p221
