#!/bin/bash
#$ -q nodes.q
#$ -R y
#$ -cwd

source /etc/profile.d/modules.sh
source /act/etc/profile.d/actbin.sh

module load mvapich2-2.1/gcc-4.9.2

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/szip/lib:/opt/armadillo-9/lib64:/opt/OpenBLAS/lib:/opt/cgal/lib:/opt/boost-1.58.0/lib:/opt/petsc-3.11.0-mpich2/lib:/opt/cuda/lib64:/opt/hdf/lib:/opt/gd/lib:/usr/lib64


/home/brandon/FronTier++/TURBULENCE/FronTierCpp/parachute/parachute -d 3 -i input-3G11/in-3G11-nVnG-box -o /home/brandon/FronTier++/TURBULENCE/FronTierCpp/parachute/out-input-3G11-serial/out-in-3G11-nVnG-box
